# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='illustrator',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
