# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_post_illustrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='illustrator',
            field=models.CharField(max_length=100),
        ),
    ]
