# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_auto_20170809_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.FileField(upload_to=''),
        ),
    ]
